import { Inter } from 'next/font/google'
import './globals.css'
import GoogleAnalytics from '../app/components/GoogleAnalytics';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'HushHaven',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      <GoogleAnalytics GA_MEASUREMENT_ID="G-3JE7WHVBXD" />
      <html lang="en">
        <body className={inter.className}>{children}<CookieBanner /></body>
      </html>
    </>
  )
}
